{
 "title": "DMG_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Select current_program_name as value from dmg_data WHERE machine_id = 3 and $__timeFilter(time)  ORDER BY time DESC;\r\nSelect\r\n  program_status::text\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "minutes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  start_up as value\r\nfrom\r\n  dmg_data\r\nWHERE\r\n  machine_id = 3 and $__timeFilter(time) \r\nORDER BY\r\n  time DESC\r\nLIMIT\r\n  1;"
    }
   ]
  },
  {
   "title": "Total Workpiece",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  total_number as value\r\nfrom\r\n  dmg_data\r\nWHERE\r\n  machine_id = 3 and $__timeFilter(time)\r\nORDER BY\r\n  time DESC\r\nLIMIT\r\n  1;"
    }
   ]
  },
  {
   "title": "Production Rate",
   "type": "stat",
   "description": "Per Day Workpieces Machined",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "WP/Day" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  total_number*60*60*24/total_cutting_time as value\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "% Current Machine Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  case when start_up = 0 then 0 else current_run_time*100/(start_up*60) end as value\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Total Cutting Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  total_cutting_time as value\r\nfrom\r\n  dmg_data\r\nWHERE\r\n  machine_id = 3 and $__timeFilter(time)\r\nORDER BY\r\n  time DESC\r\nLIMIT\r\n  1;"
    }
   ]
  },
  {
   "title": "Current Run Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  current_run_time as value\r\nfrom\r\n  dmg_data\r\nWHERE\r\n  machine_id = 3 and $__timeFilter(time)\r\nORDER BY\r\n  time DESC\r\nLIMIT\r\n  1;"
    }
   ]
  },
  {
   "title": "Current Cycle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  current_cycle as value\r\nfrom\r\n  dmg_data\r\nWHERE\r\n  machine_id = 3 and $__timeFilter(time)\r\nORDER BY\r\n  time DESC\r\nLIMIT\r\n  1;"
    }
   ]
  },
  {
   "title": "Machine On Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(EXTRACT(EPOCH FROM delta_T)) as total_on_time\r\nfrom(\r\nSELECT\r\n  on_segment,\r\n  MAX(time) - MIN(time) AS delta_T\r\nFROM\r\n  (\r\n    SELECT\r\n      time,\r\n      SUM(on_id) OVER (\r\n        ORDER BY\r\n          time\r\n      ) AS on_segment\r\n    FROM\r\n      (\r\n        SELECT\r\n          time,\r\n          CASE\r\n            WHEN machine_status = 'on'\r\n            AND LAG(machine_status) OVER (\r\n              ORDER BY\r\n                time\r\n            ) != 'on' THEN 1\r\n            ELSE 0\r\n          END AS on_id\r\n        FROM\r\n          dmg_data\r\n        where\r\n          machine_id = 3\r\n          and $__timeFilter(time)\r\n      )\r\n  )\r\nGROUP BY\r\n  on_segment\r\n  );\r\n-- SELECT \r\n--   time,\r\n--   on_segment,\r\n--   off_segment,\r\n--   machine_status\r\n--   -- MAX(time) - MIN(time) AS delta_T\r\n-- FROM(\r\n--   SELECT\r\n--     time,\r\n--     machine_status,\r\n--     SUM(off_id) OVER (\r\n--       ORDER BY\r\n--         time\r\n--     ) AS off_segment,\r\n--     SUM(on_id) OVER (\r\n--       ORDER BY\r\n--         time\r\n--     ) AS on_segment\r\n--   FROM\r\n--     (\r\n--       SELECT\r\n--         time,\r\n--         machine_status,\r\n--         CASE\r\n--           WHEN machine_status = 'off'\r\n--           AND LAG(machine_status) OVER (\r\n--             ORDER BY\r\n--               time\r\n--           ) != 'off' THEN 1\r\n--           ELSE 0\r\n--         END AS off_id,\r\n--         CASE\r\n--           WHEN machine_status = 'on'\r\n--           AND LAG(machine_status) OVER (\r\n--             ORDER BY\r\n--               time\r\n--           ) != 'on' THEN 1\r\n--           ELSE 0\r\n--         END AS on_id\r\n--       FROM\r\n--         dmg_data\r\n--       where machine_id = 3 and $__timeFilter(time)\r\n--     )\r\n--   )\r\n-- -- where on_segment > 0 and off_segment > 0\r\n-- ;"
    }
   ]
  },
  {
   "title": "Tool Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  tool_name,\r\n  tool_radius,\r\n  tool_length\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "DMG_Mori",
   "type": "grafana-iot-twinmaker-sceneviewer-panel",
   "gridPos": { "h": 14, "w": 7, "x": 9, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Machine Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "-- Select current_program_name as value from dmg_data WHERE machine_id = 3 and $__timeFilter(time)  ORDER BY time DESC;\r\nSelect\r\n  time,\r\n  program_status::text\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time;"
    }
   ]
  },
  {
   "title": "Current Program Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Select current_program_name as value from dmg_data WHERE machine_id = 3 and $__timeFilter(time)  ORDER BY time DESC;\r\nSelect\r\n  current_program_name\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Axis Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  driveload_x, driveload_y, driveload_z, driveload_c, driveload_a\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Spindle Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "Select\r\n  time, spindle_load\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time;"
    }
   ]
  },
  {
   "title": "Spindle Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  spindle_speed\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Spindle Override",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  spindle_override\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Current Program Content",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Select current_program_name as value from dmg_data WHERE machine_id = 3 and $__timeFilter(time)  ORDER BY time DESC;\r\nSelect\r\n  current_program_content\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Coordinates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  x_axis_coordinate as X_axis,\r\n  y_axis_coordinate as Y_axis,\r\n  z_axis_coordinate as Z_axis,\r\n  a_axis_coordinate as A_axis,\r\n  c_axis_coordinate as C_axis\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Feed Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mm/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  spindle_feed\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  },
  {
   "title": "Feed Override",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  feed_override\r\nfrom\r\n  dmg_data\r\nwhere\r\n  machine_id = 3\r\n  and $__timeFilter(time)\r\norder by\r\n  time desc\r\nlimit\r\n  1;"
    }
   ]
  }
 ]
}